{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clustercode.fullname" . }}-webhook
  labels:
    {{- include "clustercode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clustercode.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clustercode.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webhook
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clustercode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: webhook
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "clustercode.containerImage" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: webhook
              containerPort: 9443
              protocol: TCP
          {{- with .Values.clustercode.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - webhook
            - --webhook-tls-cert-dir=/webhook/tls
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: webhook-tls
              readOnly: true
              mountPath: /webhook/tls
      volumes:
        - name: webhook-tls
          secret:
            {{- if .Values.webhook.externalSecretName }}
            secretName: {{ .Values.webhook.externalSecretName }}
            {{- else }}
            secretName: {{ include "clustercode.fullname" . }}-webhook-tls
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
