{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clustercode.fullname" . }}-webui
  labels:
    {{- include "clustercode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      {{- include "clustercode.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clustercode.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clustercode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: webui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "clustercode.containerImage" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.clustercode.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - webui
            {{- if eq .Values.webui.api.mode "proxy" }}
            - --api-url={{ .Values.webui.api.proxy.url }}
            - --api-tls-skip-verify={{ .Values.webui.api.proxy.skipTlsVerify }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
