{{- if .Values.webui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clustercode.fullname" . }}-webui
  labels:
    {{- include "clustercode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: webui
  selector:
    {{- include "clustercode.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webui
{{- end }}
