{{- range .Values.webui.users -}}
{{- if not .skipSecret }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "clustercode.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .name }}
{{- end }}
{{- end }}
