{{- if and .Values.operator.enabled .Values.operator.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "clustercode.fullname" . }}-view'
  labels:
    {{- include "clustercode.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - clustercode.github.io
    resources:
      - blueprints
      - tasks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - clustercode.github.io
    resources:
      - blueprints/finalizers
      - blueprints/status
      - tasks/finalizers
      - tasks/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "clustercode.fullname" . }}-edit'
  labels:
    {{- include "clustercode.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - clustercode.github.io
    resources:
      - blueprints
      - tasks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - clustercode.github.io
    resources:
      - blueprints/finalizers
      - blueprints/status
      - tasks/finalizers
      - tasks/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
{{- end }}
